# Generated by Django 5.0.6 on 2024-07-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('founded', models.DateField()),
                ('division', models.CharField(choices=[('ND', '北地区'), ('ED', '東地区'), ('WD', '西地区'), ('SD', '南地区')], max_length=20)),
            ],
        ),
    ]
