# Generated by Django 5.0.6 on 2024-07-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
