# Generated by Django 5.0.6 on 2024-07-27 01:17

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('C', '捕手'), ('1B', '一塁手'), ('2B', '二塁手'), ('3B', '三塁手'), ('SS', '遊撃手'), ('LF', '左翼手'), ('CF', '中堅手'), ('RF', '右翼手'), ('DH', '指名打者')], max_length=2)),
                ('birth_date', models.DateField()),
                ('height', models.IntegerField(help_text='cmで入力してください')),
                ('weight', models.IntegerField(help_text='kgで入力してください')),
                ('batting_average', models.FloatField()),
                ('homeruns', models.IntegerField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_players', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('SP', '先発'), ('RP', '中継ぎ'), ('SU', 'セットアッパー'), ('CL', 'クローザー')], max_length=2)),
                ('birth_date', models.DateField()),
                ('height', models.IntegerField(help_text='cmで入力してください')),
                ('weight', models.IntegerField(help_text='kgで入力してください')),
                ('earned_run_average', models.FloatField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitchers', to='teams.team')),
            ],
        ),
    ]
